# Generated by Django 4.2 on 2023-07-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
