# Generated by Django 4.2 on 2023-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/default_image.jpg', null=True, upload_to='productos/'),
        ),
    ]
