# Generated by Django 4.2 on 2023-08-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
