# Generated by Django 4.2 on 2023-10-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_pedidobyuser_pedidosbyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosbyuser',
            name='pedido',
        ),
    ]
