# Generated by Django 4.2 on 2023-10-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedidosbyuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosbyuser',
            name='pedidos',
            field=models.ManyToManyField(related_name='usuarios', to='pedidos.pedidosorden'),
        ),
    ]
