# Generated by Django 4.2 on 2023-08-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0002_cupon_alter_gastosenvio_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
        model_name='correoempresa',
        name='telefono',
        field=models.CharField(max_length=15, null=True),
    ),
    ]
