# Generated by Django 4.2 on 2023-08-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0003_correoempresa_alter_cupon_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoempresa',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.PositiveIntegerField(),
        ),
    ]
