# Generated by Django 4.2 on 2023-08-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0004_alter_correoempresa_telefono_alter_cupon_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoempresa',
            name='direccion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
