# Generated by Django 4.2 on 2023-08-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0013_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
