# Generated by Django 4.2.4 on 2023-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0014_alter_cupon_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copyright',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='copyright',
            name='titulo',
        ),
        migrations.AddField(
            model_name='copyright',
            name='frase',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
