# Generated by Django 4.2 on 2023-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comprador', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('imagen', models.ImageField(help_text='La imagen debe tener al menos 200x200 píxeles.', upload_to='comentarios/')),
            ],
        ),
    ]
