# Generated by Django 4.2 on 2023-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_mensaje_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
