# Generated by Django 4.2 on 2023-10-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_mensaje_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('respondido', 'Respondido'), ('visto', 'Visto'), ('no_respondido', 'No Respondido')], default='no_respondido', max_length=20),
        ),
    ]
